### ISSUE TITLE
DOMAINS variable takes into account only the first domain

### ISSUE THREAD

**Issue by NRV90** [gchan/auto-letsencrypt#3]
Hi,

When assigning the DOMAINS env variable in the compose file, only the first domain is being processed.

Ex
DOMAINS=tbd.example.com www.tbd.example.com tbd2.example.com www.tbd2.example.com

A certificate will be requested only for the first domain:tbd.example.com

Compose sample:

environment:
        - EMAIL=tbd@tbd.com
        - WEBROOT_PATH=/data/certbot/www
        - DOMAINS=tbd.example.com www.tbd.example.com tbd2.example.com www.tbd2.example.com
        - CHECK_FREQ=7

Thank you.

**Comment by gchan** [comment]
Hi there @NRV90, 

Thanks for raising this issue.

Looks like the certbot CLI may have changed recently. Have you tried delimiting the domains with a comma separator rather than a space?

e.g. 
`DOMAINS=tbd.example.com,www.tbd.example.com,tbd2.example.com,www.tbd2.example.com`

Let me know if that works and we could work on a fix. :)

Gordon

**Comment by NRV90** [comment]
Hi,

Tried several approaches and the comma separated was one of them and still unsuccessful.

Let me know if you need more information or if there is anything I can do to help.

Thank you.

**Comment by gchan** [comment]
@NRV90, I'm having trouble replicating your issue. Can you provide any logs, output or errors you have? 

I'm thinking about bumping the base image to 1.12.0 (from 1.7.0) but uncertain if that will resolve your issue.

**Comment by NRV90** [comment]
Hi @gchan ,

I cleaned up the environment and retried. The same issue occurs. The challenge is performed for all the domains passed as parameter  but only one domain receives the certificate.

I attached the log and the compose section for certbot.

[compose.txt](https://github.com/gchan/auto-letsencrypt/files/6086959/compose.txt)
[log.txt](https://github.com/gchan/auto-letsencrypt/files/6086960/log.txt)



I apologize for the late reply.

Thank you.

**Comment by NRV90** [comment]
Hi @gchan 

Do you need me to provide more information?

Is there anything I can do to help?

Thank you.

**Comment by NRV90** [comment]
Hi @gchan ,

Having a bot for every domain is a overkill and this is what I am using to work around this issue. 

Is there any way this can be resolved?

Thank you.

**Comment by NRV90** [comment]
Hi @gchan ,

This issue can be closed.

Everything works as expected. It was a misconfiguration.

Thank you.

**Comment by gchan** [comment]
Glad you got it sorted @NRV90

Apologies for the late response!
